[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Contract AI Project"
version = "0.1.0"
description = "AI Contract Management"
authors = [
    { name = "Aj Arawwawala", email = "aj.arawwawala@paconsulting.com" }
]
